---
openapi: 3.0.2
info:
  title: cotd-api
  version: 0.0.1
  contact:
    name: Thomas Frütel
tags:
  - name: cotd-api
    description: "API for https://countryoftheday.com. Provides factual data about countries"
components:
  schemas:
    Country:
      type: object
      required:
        - type
        - id
        - attributes
      properties:
        type:
          type: string
          enum:
            - countries
        id:
          type: string
        attributes:
          type: object
          properties:
            name:
              type: string
            geography:
              type: object
              properties:
                longitude:
                  type: string
                latitude:
                  type: string
                capital:
                  type: string
                area:
                  type: integer
            languages:
              type: object
              properties:
                official:
                  type: array
                  items:
                    type: string
                spoken:
                  type: array
                  items:
                    type: string
            population:
              type: integer
    Errors:
      type: object
      description: Errors
      required:
        - errors
      properties:
        errors:
          type: array
          minItems: 1
          uniqueItems: true
          items:
            type: object
            required:
              - title
            properties:
              status:
                description: The HTTP status code applicable to this problem.
                type: string
              title:
                description:
                  A short, human-readable summary of the problem. It **SHOULD NOT**
                  change from occurrence to occurrence of the problem.
                type: string
              detail:
                description:
                  A human-readable explanation specific to this occurrence of the
                  problem.
                type: string
              code:
                description: An error code specific for this problem.
                type: string
              source:
                type: object
                properties:
                  pointer:
                    description:
                      A JSON Pointer [RFC6901] to the associated entity in the
                      request document [e.g. "/data" for a primary data object, or
                      "/data/attributes/title" for a specific attribute].
                    type: string
                  parameter:
                    description: A string indicating which query parameter caused the error.
                    type: string

paths:
  /countries/random:
    get:
      operationId: country_random
      summary: Get a random country
      tags: ["/api/cotd"]
      responses:
        "200":
          description: A random country
          content:
            application/vnd.api+json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: "#/components/schemas/Country"
        default:
          description: An error occured
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/Errors"
