apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: cotd-api
  namespace: cotd
spec:
  rules:
  - host: api.countryoftheday.com
    http:
      paths:
      - backend:
          serviceName: cotd-api
          servicePort: 80
        path: /
  tls:
  - hosts:
    - api.countryoftheday.com
    secretName: cotd-cert
